# Generated by Django 6.0.1 on 2026-06-02 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.DateTimeField()),
                ('arrival', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='active', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='companies.bus')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='companies.company')),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_destinations', to='trips.city')),
                ('origin_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_origins', to='trips.city')),
            ],
            options={
                'db_table': 'trip',
                'constraints': [models.CheckConstraint(condition=models.Q(('origin_city', models.F('destination_city')), _negated=True), name='origin-should-not-be-same-with-destination'), models.CheckConstraint(condition=models.Q(('arrival__gt', models.F('departure'))), name='arrival-must-be-after-departure'), models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='price-must-be-positive')],
            },
        ),
    ]
